OWASP/owasp.github.io

- index.md
What is OWASP. Blog excerpt of 490 chars, photo for Bay Area chapter
> Updated home page copy items

- pages/projects/projects.md
(into one not advertising Adobe)
> Change documentation project icon

- pages/corporate-sponsorships.md
The "an" in this sentence didn't make sense so I corrected it.
> Fixed spelling error

- pages/about.md
Fixed a comma error and moved an "and" to its proper location.
> Grammatical Fixes

- pages/donate.md
This update more closely aligns to the description found under "Who is the OWASP Foundation" found on the homepage. It seems to flow better.
> Restatement

- pages/sitemap.md
Fixed a link to the Web Security Testing Guide
> fix sitemap link

- pages/projects/info.md
Update link to projects Handbook
> Update link to projects Handbook

- redirects/asvs.md
> Add shortlink for ASVS

- redirects/amass.md
- redirects/asvs.md
- redirects/cheatsheet.md
- redirects/crs.md
- redirects/csrfguard.md
- redirects/defectdojo.md
- redirects/dependencycheck.md
- redirects/dependencytrack.md
- redirects/juiceshop.md
- redirects/mstg.md
- redirects/ottawa.md
- redirects/owtf.md
- redirects/samm.md
- redirects/top10.md
- redirects/wstg.md
- redirects/zap.md
Per: https://github.com/OWASP/owasp.github.io/pull/79
> Friendly Redirects for Flagships & Ottawa

- redirects/vwad.md
Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>
> Establish VWAD redirect

- index.md
Changes proposed:
1. Update in the Tags - Vulnerability Assessment
2. Relevant updates in the description
3. An update in the 'Corporate Member' Url to be consistent in URL forwarding.
> Minor updates in the home page of OWASP

- redirects/uruguay.md
Create some shortened urls for Uruguay Chapter.
> Uruguay Chapter Redirect

- pages/news.md
- pages/sitemap.md
- Add /news to the sitemap
- Remove mention of now-deprecated "Connect" on News page
Close #124
> Updates for News

- redirects/gsoc.md
`owasp.org/gsoc` -> `/www-community/initiatives/gsoc/`
Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>
> Add GSoC redirect

- pages/slack.md
Sorry I missed this earlier, it's no longer a Redirect.
> Correct slack invite page title

- pages/migration.md
Fix mailto link and link to organization
> Minor fixes

- redirects/wia.md
Setup a redirect for WIA.
Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>
> improve: Add WIA redirect

- pages/membership.md
I got tired of waiting for the membership page to be updated so I went ahead and updated the membership page to reflect that now we have a new course as a benefit.
I.e. the We Hack Purple’s Application Security Foundations Level 1 course
> OWASP Chair got tired waiting

- redirects/secureflag.md
> Fix secureflag redirect

- redirects/london.md
/london redirect for the London Chapter
> Adding London Chapter Redirect

- pages/membership.md
> Add link to OWASP leader

- _data/awards.yml
Fix typo in Rick's bio, add ZAP itself and the interview with Simon (@psiinon) and Rick (@kingthorin).
For:
https://owasp.org/awards
> Tweak WASPY award details

- pages/projects/spotlight/spotlight_more.md
> Update spotlight_more.md CWA > CWE

- _includes/member_benefits.md
AppSec Engineer informed us they have discontinued this benefit @hblankenship @kellysantalucia
> Remove AppSec Engineer

- _posts/2023-03-01-ibm-contributes-two-open-source-projects-sbom-utility-and-license-scanner-to-cyclonedx.md
@hblankenship please merge this PR between 8:30am - 8:50am Eastern on March 1 2023.
> Added CycloneDX / IBM press release

- _posts/2023-03-31-owasp-strategy-2023-1.md
I removed spacing between the ol li so that they wouldn't restart at 1 for each li.
> Attempted to fix Numbered List formatting issue

- _data/project_mediatext.json
Waiting for confirmation from @cpholguera and @sushi2k on the wording
> Update project_mediatext.json with ASVS and MAS blurb

- _data/project_mediatext.json
Per request from @hblankenship - this is an update of the DefectDojo projects metadata
> Updated media info for OWASP DefectDojo project

- redirects/lcnc-top10
I followed these examples:
https://github.com/OWASP/owasp.github.io/blob/main/redirects/top10.md
https://github.com/OWASP/owasp.github.io/blob/main/redirects/api-top10.md
> Adding a short link to LCNC Top 10

- feed.json
- feed.xml
- index.md
- rss.xml
with instruction from https://github.com/r-spatial/r-spatial.org and https://dev.to/ravgeetdhillon/create-json-feed-for-a-jekyll-blog-35p3
Hi,  thank you to the OWASP community for being such a great resource to application security teams.  
I'm interested to stay aware of what's happening with the project, and am wondering if you would accept having feeds on your website.  
All feedback is welcome
Thanks again,
Will
> Add atom, rss, and json feeds of posts directory

- _includes/member_benefits.md
Reverts OWASP/owasp.github.io#261
@kerberosmansour I think we need to revert this because according to @robvanderveer this is open to anyone with a Google account, not just OWASP members.
> Revert "Patch 4"

- _data/events.yml
Replaced the CFT submission link with the sign-up link for attendance
> Update events.yml (to provide sign-up URL)

- redirects/ottawa.md
Ensure the variant with a trailing slash doesn't 404
> Update Ottawa chapter redirect

- redirects/gsoc2021.md
- redirects/gsoc2023.md
- redirects/gsoc2024.md
- redirects/gsoc2025.md
Related to: https://github.com/OWASP/www-community/pull/1040
> GsoC 2025 Updates

- redirects/gsoc2021.md
- redirects/gsoc2023.md
- redirects/gsoc2024.md
Restore previous years GSoC related redirects
Partially revert c5601ded5375d9cfb6490a7f08563bc3055151b2
> Restore previous years GSoC related redirects

- _posts/2025-01-29-juice-shop-leadership.md
Depends on https://github.com/OWASP/www--site-theme/pull/135
> Add og_image to the most recent blog post

- _data/awards.yml
> Add Josh to page

- _includes/slack_invite.html
Inside _includes folder there is a div named div-slack-join . There is one error in css . I had corrected it.
> Fixed CSS error in slack_invite.html
